const slogans=["YOUR BOYFRIEND FOLLOWS ME","TIPS ARE MY LOVE LANGUAGE","CONTENT CREATOR — DON'T ASK WHAT KIND","YES, IT'S A REAL JOB.","DTF — DIRTY THOUGHTS FASHION","GOOD GIRLS. DIRTY THOUGHTS.","I'M THE REASON HE CLEARS HIS HISTORY","PAY ME, DON'T PLAY ME","SUBSCRIBE OR STAY CURIOUS","PRETTY EXPENSIVE","TIP FIRST. TALK LATER.","PRIVATE CONTENT. PUBLIC PROBLEM.","MY DMS HAVE A COVER CHARGE","NOT YOUR GIRL NEXT DOOR","BAD INFLUENCE","OFF THE CLOCK. STILL A PROBLEM.","I MAKE RENT LOOK EASY","CREATOR MODE: ALWAYS ON","SORRY, I'M BOOKED","YOUR FAVORITE BAD DECISION","HANDLE WITH TIPS","DTF AFTER DARK","DON'T FALL IN LOVE","PAID ATTENTION ONLY","MAKE IT WORTH MY WHILE","DIRTY THOUGHTS CLUB","TOO HOT FOR YOUR ALGORITHM","VIEW AT YOUR OWN RISK","FANTASY DEPARTMENT","I'M NOT FLIRTING. I'M NETWORKING.","PREMIUM ACCESS","GOOD TIPS, BAD IDEAS","EXCLUSIVE CONTENT","MAIN CHARACTER AFTER DARK","YOUR CRUSH SUBSCRIBES","DRESS CODE: EXPENSIVE","NO FREE PREVIEWS","DTF SOCIAL CLUB","MEMBERS ONLY ENERGY","DIRTY THOUGHTS — CLEAN FIT"];
const plan=[...Array(12).fill("T-Shirts"),...Array(7).fill("Tank Tops"),...Array(5).fill("Crop Tops"),...Array(6).fill("Hoodies"),...Array(5).fill("Sweatpants"),...Array(5).fill("Panties")];
const prices={"T-Shirts":29.99,"Tank Tops":29.99,"Crop Tops":32.99,"Hoodies":59.99,"Sweatpants":59.99,"Panties":34.99};
const imgs=["IMG_2954.jpeg","IMG_2955.jpeg","IMG_2956.jpeg","IMG_2957.jpeg","IMG_2958.jpeg","IMG_2959.jpeg"];
const products=slogans.map((s,i)=>({id:i+1,name:s,type:plan[i],price:prices[plan[i]],img:i<6?imgs[i]:null}));
let filter="All",cart=[];const grid=document.querySelector("#products"),filters=document.querySelector("#filters");
["All","T-Shirts","Tank Tops","Crop Tops","Hoodies","Sweatpants","Panties"].forEach(x=>{let b=document.createElement("button");b.textContent=x;b.className=x==="All"?"active":"";b.onclick=()=>{filter=x;[...filters.children].forEach(y=>y.classList.toggle("active",y===b));render()};filters.appendChild(b)});
function render(){grid.innerHTML="";products.filter(p=>filter==="All"||p.type===filter).forEach(p=>{let a=document.createElement("article");a.className="product";a.innerHTML='<div class="pic" '+(p.img?'style="background-image:url('+p.img+')"':'')+'><span class="type">'+p.type+'</span>'+(!p.img?'<div class="slogan">'+p.name+'</div>':'')+'</div><div class="productInfo"><h3>'+p.name+'</h3><p>'+p.type+' • DTF creator collection</p><div class="priceRow"><strong>$'+p.price.toFixed(2)+'</strong><button>ADD TO BAG</button></div></div>';a.querySelector("button").onclick=()=>add(p);grid.appendChild(a)})}
function add(p){cart.push(p);document.querySelector("#count").textContent=cart.length;drawCart();openCart()}
function drawCart(){document.querySelector("#cartItems").innerHTML=cart.map((p,i)=>'<div class="cartItem"><span>'+p.name+'<br><small>'+p.type+'</small></span><span>$'+p.price.toFixed(2)+'　<a href="#" data-r="'+i+'">×</a></span></div>').join("");document.querySelector("#subtotal").textContent="$"+cart.reduce((a,p)=>a+p.price,0).toFixed(2);document.querySelectorAll("[data-r]").forEach(a=>a.onclick=e=>{e.preventDefault();cart.splice(+a.dataset.r,1);document.querySelector("#count").textContent=cart.length;drawCart()})}
function openCart(){document.querySelector("#drawer").classList.add("open");document.querySelector("#shade").classList.add("open")}function closeCart(){document.querySelector("#drawer").classList.remove("open");document.querySelector("#shade").classList.remove("open")}document.querySelector("#cartBtn").onclick=openCart;document.querySelector("#closeCart").onclick=closeCart;document.querySelector("#shade").onclick=closeCart;document.querySelector("#checkout").onclick=()=>alert("Next step: connect payment + POD fulfillment.");render();