const http=require('http'),fs=require('fs'),path=require('path'),https=require('https');
const root=__dirname,port=process.env.PORT||8080;
function json(res,code,obj){res.writeHead(code,{'Content-Type':'application/json'});res.end(JSON.stringify(obj))}
function printify(apiPath,method='GET',body){return new Promise((resolve,reject)=>{const token=process.env.PRINTIFY_API_TOKEN;if(!token)return reject(new Error('PRINTIFY_API_TOKEN missing'));const r=https.request({hostname:'api.printify.com',path:'/v1'+apiPath,method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json','User-Agent':'DTF-Azure-Store'}},x=>{let d='';x.on('data',c=>d+=c);x.on('end',()=>{try{resolve({status:x.statusCode,data:JSON.parse(d||'{}')})}catch(e){resolve({status:x.statusCode,data:d})}})});r.on('error',reject);if(body)r.write(JSON.stringify(body));r.end()})}
const types={'.html':'text/html','.css':'text/css','.js':'application/javascript','.jpeg':'image/jpeg','.jpg':'image/jpeg','.png':'image/png','.svg':'image/svg+xml'};
http.createServer(async(req,res)=>{try{
 if(req.url==='/api/health')return json(res,200,{ok:true,printifyTokenConfigured:!!process.env.PRINTIFY_API_TOKEN});
 if(req.url==='/api/printify/shops'){const r=await printify('/shops.json');return json(res,r.status,r.data)}
 if(req.url==='/api/printify/catalog-summary'){const r=await printify('/catalog/blueprints.json');if(r.status>=400)return json(res,r.status,r.data);const words=['shirt','tank','tube','hood','sweat','jog','underwear','pant','brief'];const out=(Array.isArray(r.data)?r.data:[]).filter(x=>words.some(w=>(x.title||'').toLowerCase().includes(w))).map(x=>({id:x.id,title:x.title,brand:x.brand,model:x.model}));return json(res,200,out)}
 let u=req.url.split('?')[0];if(u==='/')u='/index.html';const f=path.normalize(path.join(root,u));if(!f.startsWith(root))return json(res,403,{error:'forbidden'});fs.readFile(f,(e,d)=>{if(e){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'Content-Type':types[path.extname(f)]||'application/octet-stream'});res.end(d)})
 }catch(e){json(res,500,{error:e.message})}}).listen(port,()=>console.log('DTF listening on '+port));