const http=require('http'),fs=require('fs'),path=require('path'),https=require('https');
const root=__dirname,port=process.env.PORT||8080;
function json(res,code,obj){res.writeHead(code,{'Content-Type':'application/json'});res.end(JSON.stringify(obj))}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
function printifyOnce(apiPath,method='GET',body){return new Promise((resolve,reject)=>{const token=process.env.PRINTIFY_API_TOKEN;if(!token)return reject(new Error('PRINTIFY_API_TOKEN missing'));const r=https.request({hostname:'api.printify.com',path:'/v1'+apiPath,method,headers:{Authorization:'Bearer '+token,Accept:'application/json','Content-Type':'application/json;charset=utf-8','User-Agent':'DTF-Azure-Store'}},x=>{let d='';x.on('data',c=>d+=c);x.on('end',()=>{try{resolve({status:x.statusCode,data:JSON.parse(d||'{}')})}catch(e){resolve({status:x.statusCode,data:d})}})});r.setTimeout(20000,()=>r.destroy(new Error('Printify request timed out')));r.on('error',reject);if(body)r.write(JSON.stringify(body));r.end()})}
async function printify(apiPath,method='GET',body){let r;for(let i=0;i<3;i++){r=await printifyOnce(apiPath,method,body);if(![500,502,503,504].includes(r.status))return r;if(i<2)await sleep(800*(i+1))}return r}
const types={'.html':'text/html','.css':'text/css','.js':'application/javascript','.jpeg':'image/jpeg','.jpg':'image/jpeg','.png':'image/png','.svg':'image/svg+xml'};
http.createServer(async(req,res)=>{try{
 const u=new URL(req.url,'http://localhost'),p=u.pathname;
 if(p==='/api/health')return json(res,200,{ok:true,printifyTokenConfigured:!!process.env.PRINTIFY_API_TOKEN});
 if(p==='/api/printify/shops'){const r=await printify('/shops.json');return json(res,r.status,r.data)}
 if(p==='/api/printify/providers'){const r=await printify('/catalog/print_providers.json');return json(res,r.status,r.data)}
 if(p.startsWith('/api/printify/blueprint/')){const id=p.split('/').pop();if(!/^\\d+$/.test(id))return json(res,400,{error:'invalid blueprint id'});const r=await printify('/catalog/blueprints/'+id+'.json');return json(res,r.status,r.data)}
 if(p==='/api/printify/dtf-candidates'){const ids=[6,18,77,407,411,1398];const results=[];for(const id of ids){const r=await printify('/catalog/blueprints/'+id+'.json');results.push({id,status:r.status,title:r.data&&r.data.title,brand:r.data&&r.data.brand,model:r.data&&r.data.model,error:r.status>=400?r.data:undefined})}return json(res,200,{ok:results.some(x=>x.status===200),results})}
 if(p==='/api/printify/catalog-summary'){const r=await printify('/catalog/blueprints.json');if(r.status>=400)return json(res,200,{ok:false,upstreamStatus:r.status,message:'Printify catalog service returned an error after 3 attempts. Authentication is still connected.',upstream:r.data});const list=Array.isArray(r.data)?r.data:(Array.isArray(r.data?.data)?r.data.data:[]);const words=['shirt','tee','tank','tube','hood','sweat','jog','underwear','pant','brief'];const out=list.filter(x=>words.some(w=>(x.title||'').toLowerCase().includes(w))).map(x=>({id:x.id,title:x.title,brand:x.brand,model:x.model,images:x.images}));return json(res,200,{ok:true,count:out.length,products:out})}
 let filePath=p;if(filePath==='/')filePath='/index.html';const f=path.normalize(path.join(root,filePath));if(!f.startsWith(root))return json(res,403,{error:'forbidden'});fs.readFile(f,(e,d)=>{if(e){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'Content-Type':types[path.extname(f)]||'application/octet-stream'});res.end(d)})
 }catch(e){json(res,500,{ok:false,error:e.message})}}).listen(port,()=>console.log('DTF listening on '+port));