# Deploy the static Dirty Thoughts Fashion site to Azure App Service
name: Deploy DTF site to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E83696E5F9414CF797CE28CBB7F339BD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_59D78DF320054278AF2A5BDCC68B58BF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A7540AF8B4D544D286BCB8D5C4112A16 }}

      - name: Deploy static site to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: dirty-thoughts-fashion
          slot-name: Production
          package: .
